{{ if .Values.metallb.enabled }}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: {{ include "rke2-openstack-calico.name" . }}-metallb-helm
spec:
  chartName: metallb
  clusterSelector:
    matchLabels:
    {{- include "rke2-openstack-calico.labels" . | nindent 6 }}
  options:
    install:
      createNamespace: true
    timeout: 5m
    wait: true
    waitForJobs: true
  namespace: metallb-system
  repoURL: oci://us-central1-docker.pkg.dev/whitestack/whitecruiser/marketplace
  credentials:
    key: config.json
    secret:
      name: oci-whitecruiser-marketplace
      namespace: fleet-default
{{- if not (empty .Values.metallb.customValues) }}
  valuesTemplate: |
    {{ toYaml .Values.metallb.customValues }}
{{- end }}
{{- end }}