apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-vip-static-pod-{{ .Values.cluster.name }}
  namespace: fleet-default
data:
  kube-vip.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: kube-vip
      namespace: kube-system
    spec:
      containers:
      - name: kube-vip
        args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: address
          value: {{ required "A valid cluster.apiServerVIP required!" .Values.cluster.apiServerVIP }}
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: cp_enable
          value: "true"
        - name: vip_nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: "ghcr.io/kube-vip/kube-vip:v0.8.9"
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - mountPath: /etc/kubernetes/admin.conf
          name: kubeconfig
      hostNetwork: true
      volumes:
      - hostPath:
          path: "/etc/rancher/rke2/rke2.yaml"
        name: kubeconfig
