apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: {{ include "rke2-openstack-calico.name" . }}-openstack-ccm-helm
spec:
  chartName: openstack-cloud-controller-manager
  clusterSelector:
    matchLabels:
    {{- include "rke2-openstack-calico.labels" . | nindent 6 }}
  options:
    install:
      createNamespace: true
    timeout: 5m
    wait: true
    waitForJobs: true
  namespace: kube-system
  repoURL: https://kubernetes.github.io/cloud-provider-openstack
  valuesTemplate: |
    nodeSelector:
    secret:
      enabled: true
      name: cloud-config
      create: false
    tolerations:
    - key: node.cloudprovider.kubernetes.io/uninitialized
      value: "true"
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
    - effect: NoSchedule
      key: node.cluster.x-k8s.io/uninitialized
    - key: "node.kubernetes.io/not-ready"
      effect: NoSchedule